#!/bin/bash
#======================================================================================
# Configure an instance of Ubuntu Linux to support Python development.
#
# Arguments:
# (None)		
#
# Version: 1.0.0
# Date: 28 Oct 2015
# Author: Dave Nicolette
#======================================================================================
export INSTALL_DIR="$HOME/provision-python-dev-ubuntu"
export COMMON_DIR="provision-ubuntu-common"
export RESOURCES="./"

git clone "git://github.com/neopragma/$COMMON_DIR"

"./$COMMON_DIR/install_build_support"
"./$COMMON_DIR/install_sublime_text_3"
"./$COMMON_DIR/install_curl"
"./$COMMON_DIR/install_aptitude"

echo
echo '============================================================='
echo 'Installing pip...'

sudo apt-get -y install python-pip

# Set the Firefox bookmarks

pushd "$HOME/.mozilla/firefox"
PROFILEDIR=$(grep -n Path profiles.ini | cut -d '=' -f 2)
cd $PROFILEDIR
cp places.sqlite places-sqlite.orig
echo
echo '============================================================='
echo 'Setting Firefox bookmarks...'
echo "Copying places.sqlite from $RESOURCES to $(pwd)"
cp "$INSTALL_DIR/places.sqlite" .
popd

echo
echo '============================================================='
echo 'Setting the desktop background image...'

mkdir -p "$HOME/.backgrounds"
cp -f "$INSTALL_DIR/python-background.png" "$HOME/.backgrounds/."
gsettings set org.gnome.desktop.background picture-uri file:///home/pythondev/.backgrounds/python-background.png

./verify


